// Code generated by MockGen. DO NOT EDIT.
// Source: liquiswiss/internal/service/db_service (interfaces: IDatabaseService)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination ../mocks/db_service.go liquiswiss/internal/service/db_service IDatabaseService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "liquiswiss/pkg/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIDatabaseService is a mock of IDatabaseService interface.
type MockIDatabaseService struct {
	ctrl     *gomock.Controller
	recorder *MockIDatabaseServiceMockRecorder
}

// MockIDatabaseServiceMockRecorder is the mock recorder for MockIDatabaseService.
type MockIDatabaseServiceMockRecorder struct {
	mock *MockIDatabaseService
}

// NewMockIDatabaseService creates a new mock instance.
func NewMockIDatabaseService(ctrl *gomock.Controller) *MockIDatabaseService {
	mock := &MockIDatabaseService{ctrl: ctrl}
	mock.recorder = &MockIDatabaseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDatabaseService) EXPECT() *MockIDatabaseServiceMockRecorder {
	return m.recorder
}

// AssignUserToOrganisation mocks base method.
func (m *MockIDatabaseService) AssignUserToOrganisation(arg0, arg1 int64, arg2 string, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUserToOrganisation", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignUserToOrganisation indicates an expected call of AssignUserToOrganisation.
func (mr *MockIDatabaseServiceMockRecorder) AssignUserToOrganisation(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUserToOrganisation", reflect.TypeOf((*MockIDatabaseService)(nil).AssignUserToOrganisation), arg0, arg1, arg2, arg3)
}

// CheckRefreshToken mocks base method.
func (m *MockIDatabaseService) CheckRefreshToken(arg0 string, arg1 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRefreshToken indicates an expected call of CheckRefreshToken.
func (mr *MockIDatabaseServiceMockRecorder) CheckRefreshToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRefreshToken", reflect.TypeOf((*MockIDatabaseService)(nil).CheckRefreshToken), arg0, arg1)
}

// CheckUserExistence mocks base method.
func (m *MockIDatabaseService) CheckUserExistence(arg0 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExistence", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserExistence indicates an expected call of CheckUserExistence.
func (mr *MockIDatabaseServiceMockRecorder) CheckUserExistence(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExistence", reflect.TypeOf((*MockIDatabaseService)(nil).CheckUserExistence), arg0)
}

// ClearForecasts mocks base method.
func (m *MockIDatabaseService) ClearForecasts(arg0 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearForecasts", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearForecasts indicates an expected call of ClearForecasts.
func (mr *MockIDatabaseServiceMockRecorder) ClearForecasts(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearForecasts", reflect.TypeOf((*MockIDatabaseService)(nil).ClearForecasts), arg0)
}

// CopyEmployeeHistoryCosts mocks base method.
func (m *MockIDatabaseService) CopyEmployeeHistoryCosts(arg0 models.CopyEmployeeHistoryCosts, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyEmployeeHistoryCosts", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyEmployeeHistoryCosts indicates an expected call of CopyEmployeeHistoryCosts.
func (mr *MockIDatabaseServiceMockRecorder) CopyEmployeeHistoryCosts(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyEmployeeHistoryCosts", reflect.TypeOf((*MockIDatabaseService)(nil).CopyEmployeeHistoryCosts), arg0, arg1, arg2)
}

// CountCurrencies mocks base method.
func (m *MockIDatabaseService) CountCurrencies() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCurrencies")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCurrencies indicates an expected call of CountCurrencies.
func (mr *MockIDatabaseServiceMockRecorder) CountCurrencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCurrencies", reflect.TypeOf((*MockIDatabaseService)(nil).CountCurrencies))
}

// CountEmployees mocks base method.
func (m *MockIDatabaseService) CountEmployees(arg0, arg1, arg2 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmployees", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmployees indicates an expected call of CountEmployees.
func (mr *MockIDatabaseServiceMockRecorder) CountEmployees(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmployees", reflect.TypeOf((*MockIDatabaseService)(nil).CountEmployees), arg0, arg1, arg2)
}

// CountUniqueCurrenciesInFiatRates mocks base method.
func (m *MockIDatabaseService) CountUniqueCurrenciesInFiatRates() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUniqueCurrenciesInFiatRates")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUniqueCurrenciesInFiatRates indicates an expected call of CountUniqueCurrenciesInFiatRates.
func (mr *MockIDatabaseServiceMockRecorder) CountUniqueCurrenciesInFiatRates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUniqueCurrenciesInFiatRates", reflect.TypeOf((*MockIDatabaseService)(nil).CountUniqueCurrenciesInFiatRates))
}

// CreateBankAccount mocks base method.
func (m *MockIDatabaseService) CreateBankAccount(arg0 models.CreateBankAccount, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankAccount", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBankAccount indicates an expected call of CreateBankAccount.
func (mr *MockIDatabaseServiceMockRecorder) CreateBankAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankAccount", reflect.TypeOf((*MockIDatabaseService)(nil).CreateBankAccount), arg0, arg1)
}

// CreateCategory mocks base method.
func (m *MockIDatabaseService) CreateCategory(arg0 *int64, arg1 models.CreateCategory) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockIDatabaseServiceMockRecorder) CreateCategory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockIDatabaseService)(nil).CreateCategory), arg0, arg1)
}

// CreateCurrency mocks base method.
func (m *MockIDatabaseService) CreateCurrency(arg0 models.CreateCurrency) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCurrency", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCurrency indicates an expected call of CreateCurrency.
func (mr *MockIDatabaseServiceMockRecorder) CreateCurrency(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCurrency", reflect.TypeOf((*MockIDatabaseService)(nil).CreateCurrency), arg0)
}

// CreateEmployee mocks base method.
func (m *MockIDatabaseService) CreateEmployee(arg0 models.CreateEmployee, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockIDatabaseServiceMockRecorder) CreateEmployee(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockIDatabaseService)(nil).CreateEmployee), arg0, arg1)
}

// CreateEmployeeHistory mocks base method.
func (m *MockIDatabaseService) CreateEmployeeHistory(arg0 models.CreateEmployeeHistory, arg1, arg2 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployeeHistory", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployeeHistory indicates an expected call of CreateEmployeeHistory.
func (mr *MockIDatabaseServiceMockRecorder) CreateEmployeeHistory(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployeeHistory", reflect.TypeOf((*MockIDatabaseService)(nil).CreateEmployeeHistory), arg0, arg1, arg2)
}

// CreateEmployeeHistoryCost mocks base method.
func (m *MockIDatabaseService) CreateEmployeeHistoryCost(arg0 models.CreateEmployeeHistoryCost, arg1, arg2 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployeeHistoryCost", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployeeHistoryCost indicates an expected call of CreateEmployeeHistoryCost.
func (mr *MockIDatabaseServiceMockRecorder) CreateEmployeeHistoryCost(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployeeHistoryCost", reflect.TypeOf((*MockIDatabaseService)(nil).CreateEmployeeHistoryCost), arg0, arg1, arg2)
}

// CreateEmployeeHistoryCostLabel mocks base method.
func (m *MockIDatabaseService) CreateEmployeeHistoryCostLabel(arg0 models.CreateEmployeeHistoryCostLabel, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployeeHistoryCostLabel", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployeeHistoryCostLabel indicates an expected call of CreateEmployeeHistoryCostLabel.
func (mr *MockIDatabaseServiceMockRecorder) CreateEmployeeHistoryCostLabel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployeeHistoryCostLabel", reflect.TypeOf((*MockIDatabaseService)(nil).CreateEmployeeHistoryCostLabel), arg0, arg1)
}

// CreateOrganisation mocks base method.
func (m *MockIDatabaseService) CreateOrganisation(arg0 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganisation", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganisation indicates an expected call of CreateOrganisation.
func (mr *MockIDatabaseServiceMockRecorder) CreateOrganisation(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganisation", reflect.TypeOf((*MockIDatabaseService)(nil).CreateOrganisation), arg0)
}

// CreateRegistration mocks base method.
func (m *MockIDatabaseService) CreateRegistration(arg0, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRegistration", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRegistration indicates an expected call of CreateRegistration.
func (mr *MockIDatabaseServiceMockRecorder) CreateRegistration(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRegistration", reflect.TypeOf((*MockIDatabaseService)(nil).CreateRegistration), arg0, arg1)
}

// CreateResetPassword mocks base method.
func (m *MockIDatabaseService) CreateResetPassword(arg0, arg1 string, arg2 time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResetPassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResetPassword indicates an expected call of CreateResetPassword.
func (mr *MockIDatabaseServiceMockRecorder) CreateResetPassword(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResetPassword", reflect.TypeOf((*MockIDatabaseService)(nil).CreateResetPassword), arg0, arg1, arg2)
}

// CreateTransaction mocks base method.
func (m *MockIDatabaseService) CreateTransaction(arg0 models.CreateTransaction, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockIDatabaseServiceMockRecorder) CreateTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockIDatabaseService)(nil).CreateTransaction), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockIDatabaseService) CreateUser(arg0, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIDatabaseServiceMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIDatabaseService)(nil).CreateUser), arg0, arg1)
}

// CreateVat mocks base method.
func (m *MockIDatabaseService) CreateVat(arg0 models.CreateVat, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVat", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVat indicates an expected call of CreateVat.
func (mr *MockIDatabaseServiceMockRecorder) CreateVat(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVat", reflect.TypeOf((*MockIDatabaseService)(nil).CreateVat), arg0, arg1)
}

// DeleteBankAccount mocks base method.
func (m *MockIDatabaseService) DeleteBankAccount(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBankAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBankAccount indicates an expected call of DeleteBankAccount.
func (mr *MockIDatabaseServiceMockRecorder) DeleteBankAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBankAccount", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteBankAccount), arg0, arg1)
}

// DeleteEmployee mocks base method.
func (m *MockIDatabaseService) DeleteEmployee(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployee", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployee indicates an expected call of DeleteEmployee.
func (mr *MockIDatabaseServiceMockRecorder) DeleteEmployee(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployee", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteEmployee), arg0, arg1)
}

// DeleteEmployeeHistory mocks base method.
func (m *MockIDatabaseService) DeleteEmployeeHistory(arg0 *models.EmployeeHistory, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployeeHistory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployeeHistory indicates an expected call of DeleteEmployeeHistory.
func (mr *MockIDatabaseServiceMockRecorder) DeleteEmployeeHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployeeHistory", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteEmployeeHistory), arg0, arg1)
}

// DeleteEmployeeHistoryCost mocks base method.
func (m *MockIDatabaseService) DeleteEmployeeHistoryCost(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployeeHistoryCost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployeeHistoryCost indicates an expected call of DeleteEmployeeHistoryCost.
func (mr *MockIDatabaseServiceMockRecorder) DeleteEmployeeHistoryCost(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployeeHistoryCost", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteEmployeeHistoryCost), arg0, arg1)
}

// DeleteEmployeeHistoryCostLabel mocks base method.
func (m *MockIDatabaseService) DeleteEmployeeHistoryCostLabel(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployeeHistoryCostLabel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployeeHistoryCostLabel indicates an expected call of DeleteEmployeeHistoryCostLabel.
func (mr *MockIDatabaseServiceMockRecorder) DeleteEmployeeHistoryCostLabel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployeeHistoryCostLabel", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteEmployeeHistoryCostLabel), arg0, arg1)
}

// DeleteRefreshToken mocks base method.
func (m *MockIDatabaseService) DeleteRefreshToken(arg0 string, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockIDatabaseServiceMockRecorder) DeleteRefreshToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteRefreshToken), arg0, arg1)
}

// DeleteRegistration mocks base method.
func (m *MockIDatabaseService) DeleteRegistration(arg0 int64, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegistration", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegistration indicates an expected call of DeleteRegistration.
func (mr *MockIDatabaseServiceMockRecorder) DeleteRegistration(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegistration", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteRegistration), arg0, arg1)
}

// DeleteResetPassword mocks base method.
func (m *MockIDatabaseService) DeleteResetPassword(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResetPassword", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResetPassword indicates an expected call of DeleteResetPassword.
func (mr *MockIDatabaseServiceMockRecorder) DeleteResetPassword(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResetPassword", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteResetPassword), arg0)
}

// DeleteTransaction mocks base method.
func (m *MockIDatabaseService) DeleteTransaction(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockIDatabaseServiceMockRecorder) DeleteTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteTransaction), arg0, arg1)
}

// DeleteVat mocks base method.
func (m *MockIDatabaseService) DeleteVat(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVat", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVat indicates an expected call of DeleteVat.
func (mr *MockIDatabaseServiceMockRecorder) DeleteVat(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVat", reflect.TypeOf((*MockIDatabaseService)(nil).DeleteVat), arg0, arg1)
}

// GetBankAccount mocks base method.
func (m *MockIDatabaseService) GetBankAccount(arg0, arg1 int64) (*models.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankAccount", arg0, arg1)
	ret0, _ := ret[0].(*models.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankAccount indicates an expected call of GetBankAccount.
func (mr *MockIDatabaseServiceMockRecorder) GetBankAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankAccount", reflect.TypeOf((*MockIDatabaseService)(nil).GetBankAccount), arg0, arg1)
}

// GetCategory mocks base method.
func (m *MockIDatabaseService) GetCategory(arg0, arg1 int64) (*models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", arg0, arg1)
	ret0, _ := ret[0].(*models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockIDatabaseServiceMockRecorder) GetCategory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockIDatabaseService)(nil).GetCategory), arg0, arg1)
}

// GetCurrency mocks base method.
func (m *MockIDatabaseService) GetCurrency(arg0 int64) (*models.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency", arg0)
	ret0, _ := ret[0].(*models.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrency indicates an expected call of GetCurrency.
func (mr *MockIDatabaseServiceMockRecorder) GetCurrency(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockIDatabaseService)(nil).GetCurrency), arg0)
}

// GetEmployee mocks base method.
func (m *MockIDatabaseService) GetEmployee(arg0, arg1 int64) (*models.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployee", arg0, arg1)
	ret0, _ := ret[0].(*models.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployee indicates an expected call of GetEmployee.
func (mr *MockIDatabaseServiceMockRecorder) GetEmployee(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployee", reflect.TypeOf((*MockIDatabaseService)(nil).GetEmployee), arg0, arg1)
}

// GetEmployeeHistory mocks base method.
func (m *MockIDatabaseService) GetEmployeeHistory(arg0, arg1 int64) (*models.EmployeeHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeHistory", arg0, arg1)
	ret0, _ := ret[0].(*models.EmployeeHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeHistory indicates an expected call of GetEmployeeHistory.
func (mr *MockIDatabaseServiceMockRecorder) GetEmployeeHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeHistory", reflect.TypeOf((*MockIDatabaseService)(nil).GetEmployeeHistory), arg0, arg1)
}

// GetEmployeeHistoryCost mocks base method.
func (m *MockIDatabaseService) GetEmployeeHistoryCost(arg0, arg1 int64) (*models.EmployeeHistoryCost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeHistoryCost", arg0, arg1)
	ret0, _ := ret[0].(*models.EmployeeHistoryCost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeHistoryCost indicates an expected call of GetEmployeeHistoryCost.
func (mr *MockIDatabaseServiceMockRecorder) GetEmployeeHistoryCost(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeHistoryCost", reflect.TypeOf((*MockIDatabaseService)(nil).GetEmployeeHistoryCost), arg0, arg1)
}

// GetEmployeeHistoryCostLabel mocks base method.
func (m *MockIDatabaseService) GetEmployeeHistoryCostLabel(arg0, arg1 int64) (*models.EmployeeHistoryCostLabel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeHistoryCostLabel", arg0, arg1)
	ret0, _ := ret[0].(*models.EmployeeHistoryCostLabel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeHistoryCostLabel indicates an expected call of GetEmployeeHistoryCostLabel.
func (mr *MockIDatabaseServiceMockRecorder) GetEmployeeHistoryCostLabel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeHistoryCostLabel", reflect.TypeOf((*MockIDatabaseService)(nil).GetEmployeeHistoryCostLabel), arg0, arg1)
}

// GetFiatRate mocks base method.
func (m *MockIDatabaseService) GetFiatRate(arg0, arg1 string) (*models.FiatRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFiatRate", arg0, arg1)
	ret0, _ := ret[0].(*models.FiatRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFiatRate indicates an expected call of GetFiatRate.
func (mr *MockIDatabaseServiceMockRecorder) GetFiatRate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFiatRate", reflect.TypeOf((*MockIDatabaseService)(nil).GetFiatRate), arg0, arg1)
}

// GetOrganisation mocks base method.
func (m *MockIDatabaseService) GetOrganisation(arg0, arg1 int64) (*models.Organisation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganisation", arg0, arg1)
	ret0, _ := ret[0].(*models.Organisation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganisation indicates an expected call of GetOrganisation.
func (mr *MockIDatabaseServiceMockRecorder) GetOrganisation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganisation", reflect.TypeOf((*MockIDatabaseService)(nil).GetOrganisation), arg0, arg1)
}

// GetProfile mocks base method.
func (m *MockIDatabaseService) GetProfile(arg0 int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockIDatabaseServiceMockRecorder) GetProfile(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockIDatabaseService)(nil).GetProfile), arg0)
}

// GetTransaction mocks base method.
func (m *MockIDatabaseService) GetTransaction(arg0, arg1 int64) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", arg0, arg1)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockIDatabaseServiceMockRecorder) GetTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockIDatabaseService)(nil).GetTransaction), arg0, arg1)
}

// GetUserPasswordByEMail mocks base method.
func (m *MockIDatabaseService) GetUserPasswordByEMail(arg0 string) (*models.Login, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPasswordByEMail", arg0)
	ret0, _ := ret[0].(*models.Login)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPasswordByEMail indicates an expected call of GetUserPasswordByEMail.
func (mr *MockIDatabaseServiceMockRecorder) GetUserPasswordByEMail(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPasswordByEMail", reflect.TypeOf((*MockIDatabaseService)(nil).GetUserPasswordByEMail), arg0)
}

// GetVat mocks base method.
func (m *MockIDatabaseService) GetVat(arg0, arg1 int64) (*models.Vat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVat", arg0, arg1)
	ret0, _ := ret[0].(*models.Vat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVat indicates an expected call of GetVat.
func (mr *MockIDatabaseServiceMockRecorder) GetVat(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVat", reflect.TypeOf((*MockIDatabaseService)(nil).GetVat), arg0, arg1)
}

// ListBankAccounts mocks base method.
func (m *MockIDatabaseService) ListBankAccounts(arg0 int64) ([]models.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBankAccounts", arg0)
	ret0, _ := ret[0].([]models.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBankAccounts indicates an expected call of ListBankAccounts.
func (mr *MockIDatabaseServiceMockRecorder) ListBankAccounts(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBankAccounts", reflect.TypeOf((*MockIDatabaseService)(nil).ListBankAccounts), arg0)
}

// ListCategories mocks base method.
func (m *MockIDatabaseService) ListCategories(arg0, arg1, arg2 int64) ([]models.Category, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockIDatabaseServiceMockRecorder) ListCategories(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockIDatabaseService)(nil).ListCategories), arg0, arg1, arg2)
}

// ListCurrencies mocks base method.
func (m *MockIDatabaseService) ListCurrencies(arg0, arg1, arg2 int64) ([]models.Currency, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCurrencies", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Currency)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCurrencies indicates an expected call of ListCurrencies.
func (mr *MockIDatabaseServiceMockRecorder) ListCurrencies(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCurrencies", reflect.TypeOf((*MockIDatabaseService)(nil).ListCurrencies), arg0, arg1, arg2)
}

// ListEmployeeHistory mocks base method.
func (m *MockIDatabaseService) ListEmployeeHistory(arg0, arg1, arg2, arg3 int64) ([]models.EmployeeHistory, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeeHistory", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.EmployeeHistory)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEmployeeHistory indicates an expected call of ListEmployeeHistory.
func (mr *MockIDatabaseServiceMockRecorder) ListEmployeeHistory(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeeHistory", reflect.TypeOf((*MockIDatabaseService)(nil).ListEmployeeHistory), arg0, arg1, arg2, arg3)
}

// ListEmployeeHistoryCostLabels mocks base method.
func (m *MockIDatabaseService) ListEmployeeHistoryCostLabels(arg0, arg1, arg2 int64) ([]models.EmployeeHistoryCostLabel, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeeHistoryCostLabels", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.EmployeeHistoryCostLabel)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEmployeeHistoryCostLabels indicates an expected call of ListEmployeeHistoryCostLabels.
func (mr *MockIDatabaseServiceMockRecorder) ListEmployeeHistoryCostLabels(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeeHistoryCostLabels", reflect.TypeOf((*MockIDatabaseService)(nil).ListEmployeeHistoryCostLabels), arg0, arg1, arg2)
}

// ListEmployeeHistoryCosts mocks base method.
func (m *MockIDatabaseService) ListEmployeeHistoryCosts(arg0, arg1, arg2, arg3 int64) ([]models.EmployeeHistoryCost, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeeHistoryCosts", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.EmployeeHistoryCost)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEmployeeHistoryCosts indicates an expected call of ListEmployeeHistoryCosts.
func (mr *MockIDatabaseServiceMockRecorder) ListEmployeeHistoryCosts(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeeHistoryCosts", reflect.TypeOf((*MockIDatabaseService)(nil).ListEmployeeHistoryCosts), arg0, arg1, arg2, arg3)
}

// ListEmployees mocks base method.
func (m *MockIDatabaseService) ListEmployees(arg0, arg1, arg2 int64, arg3, arg4 string) ([]models.Employee, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployees", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.Employee)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEmployees indicates an expected call of ListEmployees.
func (mr *MockIDatabaseServiceMockRecorder) ListEmployees(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployees", reflect.TypeOf((*MockIDatabaseService)(nil).ListEmployees), arg0, arg1, arg2, arg3, arg4)
}

// ListFiatRates mocks base method.
func (m *MockIDatabaseService) ListFiatRates(arg0 string) ([]models.FiatRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiatRates", arg0)
	ret0, _ := ret[0].([]models.FiatRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiatRates indicates an expected call of ListFiatRates.
func (mr *MockIDatabaseServiceMockRecorder) ListFiatRates(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiatRates", reflect.TypeOf((*MockIDatabaseService)(nil).ListFiatRates), arg0)
}

// ListForecastDetails mocks base method.
func (m *MockIDatabaseService) ListForecastDetails(arg0, arg1 int64) ([]models.ForecastDatabaseDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForecastDetails", arg0, arg1)
	ret0, _ := ret[0].([]models.ForecastDatabaseDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForecastDetails indicates an expected call of ListForecastDetails.
func (mr *MockIDatabaseServiceMockRecorder) ListForecastDetails(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForecastDetails", reflect.TypeOf((*MockIDatabaseService)(nil).ListForecastDetails), arg0, arg1)
}

// ListForecasts mocks base method.
func (m *MockIDatabaseService) ListForecasts(arg0, arg1 int64) ([]models.Forecast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForecasts", arg0, arg1)
	ret0, _ := ret[0].([]models.Forecast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForecasts indicates an expected call of ListForecasts.
func (mr *MockIDatabaseServiceMockRecorder) ListForecasts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForecasts", reflect.TypeOf((*MockIDatabaseService)(nil).ListForecasts), arg0, arg1)
}

// ListOrganisations mocks base method.
func (m *MockIDatabaseService) ListOrganisations(arg0, arg1, arg2 int64) ([]models.Organisation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganisations", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Organisation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrganisations indicates an expected call of ListOrganisations.
func (mr *MockIDatabaseServiceMockRecorder) ListOrganisations(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganisations", reflect.TypeOf((*MockIDatabaseService)(nil).ListOrganisations), arg0, arg1, arg2)
}

// ListTransactions mocks base method.
func (m *MockIDatabaseService) ListTransactions(arg0, arg1, arg2 int64, arg3, arg4 string) ([]models.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockIDatabaseServiceMockRecorder) ListTransactions(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockIDatabaseService)(nil).ListTransactions), arg0, arg1, arg2, arg3, arg4)
}

// ListVats mocks base method.
func (m *MockIDatabaseService) ListVats(arg0 int64) ([]models.Vat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVats", arg0)
	ret0, _ := ret[0].([]models.Vat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVats indicates an expected call of ListVats.
func (mr *MockIDatabaseServiceMockRecorder) ListVats(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVats", reflect.TypeOf((*MockIDatabaseService)(nil).ListVats), arg0)
}

// ResetPassword mocks base method.
func (m *MockIDatabaseService) ResetPassword(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockIDatabaseServiceMockRecorder) ResetPassword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockIDatabaseService)(nil).ResetPassword), arg0, arg1)
}

// SetUserCurrentOrganisation mocks base method.
func (m *MockIDatabaseService) SetUserCurrentOrganisation(arg0, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserCurrentOrganisation", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserCurrentOrganisation indicates an expected call of SetUserCurrentOrganisation.
func (mr *MockIDatabaseServiceMockRecorder) SetUserCurrentOrganisation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserCurrentOrganisation", reflect.TypeOf((*MockIDatabaseService)(nil).SetUserCurrentOrganisation), arg0, arg1)
}

// StoreRefreshTokenID mocks base method.
func (m *MockIDatabaseService) StoreRefreshTokenID(arg0 int64, arg1 string, arg2 time.Time, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefreshTokenID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefreshTokenID indicates an expected call of StoreRefreshTokenID.
func (mr *MockIDatabaseServiceMockRecorder) StoreRefreshTokenID(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefreshTokenID", reflect.TypeOf((*MockIDatabaseService)(nil).StoreRefreshTokenID), arg0, arg1, arg2, arg3)
}

// UpdateBankAccount mocks base method.
func (m *MockIDatabaseService) UpdateBankAccount(arg0 models.UpdateBankAccount, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBankAccount", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBankAccount indicates an expected call of UpdateBankAccount.
func (mr *MockIDatabaseServiceMockRecorder) UpdateBankAccount(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBankAccount", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateBankAccount), arg0, arg1, arg2)
}

// UpdateCategory mocks base method.
func (m *MockIDatabaseService) UpdateCategory(arg0 int64, arg1 models.UpdateCategory, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockIDatabaseServiceMockRecorder) UpdateCategory(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateCategory), arg0, arg1, arg2)
}

// UpdateCurrency mocks base method.
func (m *MockIDatabaseService) UpdateCurrency(arg0 models.UpdateCurrency, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrency", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCurrency indicates an expected call of UpdateCurrency.
func (mr *MockIDatabaseServiceMockRecorder) UpdateCurrency(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrency", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateCurrency), arg0, arg1)
}

// UpdateEmployee mocks base method.
func (m *MockIDatabaseService) UpdateEmployee(arg0 models.UpdateEmployee, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployee", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmployee indicates an expected call of UpdateEmployee.
func (mr *MockIDatabaseServiceMockRecorder) UpdateEmployee(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployee", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateEmployee), arg0, arg1, arg2)
}

// UpdateEmployeeHistory mocks base method.
func (m *MockIDatabaseService) UpdateEmployeeHistory(arg0 models.UpdateEmployeeHistory, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployeeHistory", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmployeeHistory indicates an expected call of UpdateEmployeeHistory.
func (mr *MockIDatabaseServiceMockRecorder) UpdateEmployeeHistory(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployeeHistory", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateEmployeeHistory), arg0, arg1, arg2)
}

// UpdateEmployeeHistoryCost mocks base method.
func (m *MockIDatabaseService) UpdateEmployeeHistoryCost(arg0 models.CreateEmployeeHistoryCost, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployeeHistoryCost", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmployeeHistoryCost indicates an expected call of UpdateEmployeeHistoryCost.
func (mr *MockIDatabaseServiceMockRecorder) UpdateEmployeeHistoryCost(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployeeHistoryCost", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateEmployeeHistoryCost), arg0, arg1, arg2)
}

// UpdateEmployeeHistoryCostLabel mocks base method.
func (m *MockIDatabaseService) UpdateEmployeeHistoryCostLabel(arg0 models.CreateEmployeeHistoryCostLabel, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployeeHistoryCostLabel", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmployeeHistoryCostLabel indicates an expected call of UpdateEmployeeHistoryCostLabel.
func (mr *MockIDatabaseServiceMockRecorder) UpdateEmployeeHistoryCostLabel(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployeeHistoryCostLabel", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateEmployeeHistoryCostLabel), arg0, arg1, arg2)
}

// UpdateOrganisation mocks base method.
func (m *MockIDatabaseService) UpdateOrganisation(arg0 models.UpdateOrganisation, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganisation", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrganisation indicates an expected call of UpdateOrganisation.
func (mr *MockIDatabaseServiceMockRecorder) UpdateOrganisation(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganisation", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateOrganisation), arg0, arg1, arg2)
}

// UpdatePassword mocks base method.
func (m *MockIDatabaseService) UpdatePassword(arg0 string, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockIDatabaseServiceMockRecorder) UpdatePassword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockIDatabaseService)(nil).UpdatePassword), arg0, arg1)
}

// UpdateProfile mocks base method.
func (m *MockIDatabaseService) UpdateProfile(arg0 models.UpdateUser, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockIDatabaseServiceMockRecorder) UpdateProfile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateProfile), arg0, arg1)
}

// UpdateTransaction mocks base method.
func (m *MockIDatabaseService) UpdateTransaction(arg0 models.UpdateTransaction, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockIDatabaseServiceMockRecorder) UpdateTransaction(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateTransaction), arg0, arg1, arg2)
}

// UpdateVat mocks base method.
func (m *MockIDatabaseService) UpdateVat(arg0 models.UpdateVat, arg1, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVat", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVat indicates an expected call of UpdateVat.
func (mr *MockIDatabaseServiceMockRecorder) UpdateVat(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVat", reflect.TypeOf((*MockIDatabaseService)(nil).UpdateVat), arg0, arg1, arg2)
}

// UpsertFiatRate mocks base method.
func (m *MockIDatabaseService) UpsertFiatRate(arg0 models.CreateFiatRate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFiatRate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFiatRate indicates an expected call of UpsertFiatRate.
func (mr *MockIDatabaseServiceMockRecorder) UpsertFiatRate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFiatRate", reflect.TypeOf((*MockIDatabaseService)(nil).UpsertFiatRate), arg0)
}

// UpsertForecast mocks base method.
func (m *MockIDatabaseService) UpsertForecast(arg0 models.CreateForecast, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertForecast", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertForecast indicates an expected call of UpsertForecast.
func (mr *MockIDatabaseServiceMockRecorder) UpsertForecast(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertForecast", reflect.TypeOf((*MockIDatabaseService)(nil).UpsertForecast), arg0, arg1)
}

// UpsertForecastDetail mocks base method.
func (m *MockIDatabaseService) UpsertForecastDetail(arg0 models.CreateForecastDetail, arg1, arg2 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertForecastDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertForecastDetail indicates an expected call of UpsertForecastDetail.
func (mr *MockIDatabaseServiceMockRecorder) UpsertForecastDetail(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertForecastDetail", reflect.TypeOf((*MockIDatabaseService)(nil).UpsertForecastDetail), arg0, arg1, arg2)
}

// ValidateRegistration mocks base method.
func (m *MockIDatabaseService) ValidateRegistration(arg0, arg1 string, arg2 time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRegistration", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRegistration indicates an expected call of ValidateRegistration.
func (mr *MockIDatabaseServiceMockRecorder) ValidateRegistration(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRegistration", reflect.TypeOf((*MockIDatabaseService)(nil).ValidateRegistration), arg0, arg1, arg2)
}

// ValidateResetPassword mocks base method.
func (m *MockIDatabaseService) ValidateResetPassword(arg0, arg1 string, arg2 time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateResetPassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateResetPassword indicates an expected call of ValidateResetPassword.
func (mr *MockIDatabaseServiceMockRecorder) ValidateResetPassword(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateResetPassword", reflect.TypeOf((*MockIDatabaseService)(nil).ValidateResetPassword), arg0, arg1, arg2)
}
