services:
#  nuxt:
#    build:
#      dockerfile: .deploy/nuxt/Dockerfile
#      context: .
#      target: dev
#    restart: always
#    ports:
#      - '3000:3000'
#    environment:
#      # This is great for testing with different timezones. Leave empty for UTC
#      - TZ=Europe/Berlin
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#
#  backend:
#    image: golang:1.23.3-alpine
#    restart: always
#    depends_on:
#      - database
#    ports:
#      - '8080:8080'
#    working_dir: /app
#    environment:
#      # This is great for testing with different timezones. Leave empty for UTC
#      - TZ=Europe/Berlin
#    volumes:
#      - ./backend:/app

  database:
    image: mariadb:10.6.16
    restart: always
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: ls_user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: liquiswiss
    volumes:
      - ./db_data:/var/lib/mysql
