// Code generated by MockGen. DO NOT EDIT.
// Source: liquiswiss/internal/adapter/aigent_adapter (interfaces: IAigentAdapter)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination ../../mocks/aigent_adapter.go liquiswiss/internal/adapter/aigent_adapter IAigentAdapter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "liquiswiss/pkg/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAigentAdapter is a mock of IAigentAdapter interface.
type MockIAigentAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockIAigentAdapterMockRecorder
	isgomock struct{}
}

// MockIAigentAdapterMockRecorder is the mock recorder for MockIAigentAdapter.
type MockIAigentAdapterMockRecorder struct {
	mock *MockIAigentAdapter
}

// NewMockIAigentAdapter creates a new mock instance.
func NewMockIAigentAdapter(ctrl *gomock.Controller) *MockIAigentAdapter {
	mock := &MockIAigentAdapter{ctrl: ctrl}
	mock.recorder = &MockIAigentAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAigentAdapter) EXPECT() *MockIAigentAdapterMockRecorder {
	return m.recorder
}

// CreateChatbot mocks base method.
func (m *MockIAigentAdapter) CreateChatbot(req models.AigentCreateChatbotRequest) (*models.AigentCreateChatbotResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatbot", req)
	ret0, _ := ret[0].(*models.AigentCreateChatbotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatbot indicates an expected call of CreateChatbot.
func (mr *MockIAigentAdapterMockRecorder) CreateChatbot(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatbot", reflect.TypeOf((*MockIAigentAdapter)(nil).CreateChatbot), req)
}

// CreateMCPServer mocks base method.
func (m *MockIAigentAdapter) CreateMCPServer(skillID string, req models.AigentCreateMCPServerRequest) (*models.AigentMCPServerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMCPServer", skillID, req)
	ret0, _ := ret[0].(*models.AigentMCPServerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMCPServer indicates an expected call of CreateMCPServer.
func (mr *MockIAigentAdapterMockRecorder) CreateMCPServer(skillID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMCPServer", reflect.TypeOf((*MockIAigentAdapter)(nil).CreateMCPServer), skillID, req)
}

// CreateSkill mocks base method.
func (m *MockIAigentAdapter) CreateSkill(req models.AigentCreateSkillRequest) (*models.AigentCreateSkillResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSkill", req)
	ret0, _ := ret[0].(*models.AigentCreateSkillResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSkill indicates an expected call of CreateSkill.
func (mr *MockIAigentAdapterMockRecorder) CreateSkill(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSkill", reflect.TypeOf((*MockIAigentAdapter)(nil).CreateSkill), req)
}

// DeleteChatbot mocks base method.
func (m *MockIAigentAdapter) DeleteChatbot(chatID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChatbot", chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChatbot indicates an expected call of DeleteChatbot.
func (mr *MockIAigentAdapterMockRecorder) DeleteChatbot(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChatbot", reflect.TypeOf((*MockIAigentAdapter)(nil).DeleteChatbot), chatID)
}

// DeleteSkill mocks base method.
func (m *MockIAigentAdapter) DeleteSkill(skillID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSkill", skillID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSkill indicates an expected call of DeleteSkill.
func (mr *MockIAigentAdapterMockRecorder) DeleteSkill(skillID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSkill", reflect.TypeOf((*MockIAigentAdapter)(nil).DeleteSkill), skillID)
}

// SendMessage mocks base method.
func (m *MockIAigentAdapter) SendMessage(chatID, query, sessionID string) (*models.AigentChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", chatID, query, sessionID)
	ret0, _ := ret[0].(*models.AigentChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockIAigentAdapterMockRecorder) SendMessage(chatID, query, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockIAigentAdapter)(nil).SendMessage), chatID, query, sessionID)
}

// UpdateChatbot mocks base method.
func (m *MockIAigentAdapter) UpdateChatbot(chatbotID string, req models.AigentUpdateChatbotRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChatbot", chatbotID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChatbot indicates an expected call of UpdateChatbot.
func (mr *MockIAigentAdapterMockRecorder) UpdateChatbot(chatbotID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChatbot", reflect.TypeOf((*MockIAigentAdapter)(nil).UpdateChatbot), chatbotID, req)
}
