// Code generated by MockGen. DO NOT EDIT.
// Source: liquiswiss/internal/adapter/db_adapter (interfaces: IDatabaseAdapter)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination ../../mocks/db_adapter.go liquiswiss/internal/adapter/db_adapter IDatabaseAdapter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "liquiswiss/pkg/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIDatabaseAdapter is a mock of IDatabaseAdapter interface.
type MockIDatabaseAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockIDatabaseAdapterMockRecorder
	isgomock struct{}
}

// MockIDatabaseAdapterMockRecorder is the mock recorder for MockIDatabaseAdapter.
type MockIDatabaseAdapterMockRecorder struct {
	mock *MockIDatabaseAdapter
}

// NewMockIDatabaseAdapter creates a new mock instance.
func NewMockIDatabaseAdapter(ctrl *gomock.Controller) *MockIDatabaseAdapter {
	mock := &MockIDatabaseAdapter{ctrl: ctrl}
	mock.recorder = &MockIDatabaseAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDatabaseAdapter) EXPECT() *MockIDatabaseAdapterMockRecorder {
	return m.recorder
}

// AssignUserToOrganisation mocks base method.
func (m *MockIDatabaseAdapter) AssignUserToOrganisation(userID, organisationID int64, role string, isDefault bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUserToOrganisation", userID, organisationID, role, isDefault)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignUserToOrganisation indicates an expected call of AssignUserToOrganisation.
func (mr *MockIDatabaseAdapterMockRecorder) AssignUserToOrganisation(userID, organisationID, role, isDefault any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUserToOrganisation", reflect.TypeOf((*MockIDatabaseAdapter)(nil).AssignUserToOrganisation), userID, organisationID, role, isDefault)
}

// CalculateSalaryCostDetails mocks base method.
func (m *MockIDatabaseAdapter) CalculateSalaryCostDetails(userID, salaryCostID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateSalaryCostDetails", userID, salaryCostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CalculateSalaryCostDetails indicates an expected call of CalculateSalaryCostDetails.
func (mr *MockIDatabaseAdapterMockRecorder) CalculateSalaryCostDetails(userID, salaryCostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateSalaryCostDetails", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CalculateSalaryCostDetails), userID, salaryCostID)
}

// CheckRefreshToken mocks base method.
func (m *MockIDatabaseAdapter) CheckRefreshToken(userID int64, tokenID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRefreshToken", userID, tokenID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRefreshToken indicates an expected call of CheckRefreshToken.
func (mr *MockIDatabaseAdapterMockRecorder) CheckRefreshToken(userID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRefreshToken", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CheckRefreshToken), userID, tokenID)
}

// CheckUserExistence mocks base method.
func (m *MockIDatabaseAdapter) CheckUserExistence(id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExistence", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserExistence indicates an expected call of CheckUserExistence.
func (mr *MockIDatabaseAdapterMockRecorder) CheckUserExistence(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExistence", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CheckUserExistence), id)
}

// ClearForecasts mocks base method.
func (m *MockIDatabaseAdapter) ClearForecasts(userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearForecasts", userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearForecasts indicates an expected call of ClearForecasts.
func (mr *MockIDatabaseAdapterMockRecorder) ClearForecasts(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearForecasts", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ClearForecasts), userID)
}

// CopySalaryCosts mocks base method.
func (m *MockIDatabaseAdapter) CopySalaryCosts(payload models.CopySalaryCosts, userID, salaryID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopySalaryCosts", payload, userID, salaryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopySalaryCosts indicates an expected call of CopySalaryCosts.
func (mr *MockIDatabaseAdapterMockRecorder) CopySalaryCosts(payload, userID, salaryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopySalaryCosts", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CopySalaryCosts), payload, userID, salaryID)
}

// CopyScenarioData mocks base method.
func (m *MockIDatabaseAdapter) CopyScenarioData(sourceScenarioID, targetScenarioID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyScenarioData", sourceScenarioID, targetScenarioID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyScenarioData indicates an expected call of CopyScenarioData.
func (mr *MockIDatabaseAdapterMockRecorder) CopyScenarioData(sourceScenarioID, targetScenarioID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyScenarioData", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CopyScenarioData), sourceScenarioID, targetScenarioID, userID)
}

// CountCurrencies mocks base method.
func (m *MockIDatabaseAdapter) CountCurrencies() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCurrencies")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCurrencies indicates an expected call of CountCurrencies.
func (mr *MockIDatabaseAdapterMockRecorder) CountCurrencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCurrencies", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CountCurrencies))
}

// CountEmployees mocks base method.
func (m *MockIDatabaseAdapter) CountEmployees(userID, page, limit int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmployees", userID, page, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmployees indicates an expected call of CountEmployees.
func (mr *MockIDatabaseAdapterMockRecorder) CountEmployees(userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmployees", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CountEmployees), userID, page, limit)
}

// CountUniqueCurrenciesInFiatRates mocks base method.
func (m *MockIDatabaseAdapter) CountUniqueCurrenciesInFiatRates() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUniqueCurrenciesInFiatRates")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUniqueCurrenciesInFiatRates indicates an expected call of CountUniqueCurrenciesInFiatRates.
func (mr *MockIDatabaseAdapterMockRecorder) CountUniqueCurrenciesInFiatRates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUniqueCurrenciesInFiatRates", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CountUniqueCurrenciesInFiatRates))
}

// CreateBankAccount mocks base method.
func (m *MockIDatabaseAdapter) CreateBankAccount(payload models.CreateBankAccount, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankAccount", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBankAccount indicates an expected call of CreateBankAccount.
func (mr *MockIDatabaseAdapterMockRecorder) CreateBankAccount(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankAccount", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateBankAccount), payload, userID)
}

// CreateCategory mocks base method.
func (m *MockIDatabaseAdapter) CreateCategory(payload models.CreateCategory, userID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockIDatabaseAdapterMockRecorder) CreateCategory(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateCategory), payload, userID)
}

// CreateCurrency mocks base method.
func (m *MockIDatabaseAdapter) CreateCurrency(payload models.CreateCurrency) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCurrency", payload)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCurrency indicates an expected call of CreateCurrency.
func (mr *MockIDatabaseAdapterMockRecorder) CreateCurrency(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCurrency", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateCurrency), payload)
}

// CreateEmployee mocks base method.
func (m *MockIDatabaseAdapter) CreateEmployee(payload models.CreateEmployee, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockIDatabaseAdapterMockRecorder) CreateEmployee(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateEmployee), payload, userID)
}

// CreateForecastExclusion mocks base method.
func (m *MockIDatabaseAdapter) CreateForecastExclusion(payload models.CreateForecastExclusion, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForecastExclusion", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateForecastExclusion indicates an expected call of CreateForecastExclusion.
func (mr *MockIDatabaseAdapterMockRecorder) CreateForecastExclusion(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForecastExclusion", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateForecastExclusion), payload, userID)
}

// CreateOrganisation mocks base method.
func (m *MockIDatabaseAdapter) CreateOrganisation(name string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganisation", name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganisation indicates an expected call of CreateOrganisation.
func (mr *MockIDatabaseAdapterMockRecorder) CreateOrganisation(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganisation", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateOrganisation), name)
}

// CreateRegistration mocks base method.
func (m *MockIDatabaseAdapter) CreateRegistration(email, code string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRegistration", email, code)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRegistration indicates an expected call of CreateRegistration.
func (mr *MockIDatabaseAdapterMockRecorder) CreateRegistration(email, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRegistration", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateRegistration), email, code)
}

// CreateResetPassword mocks base method.
func (m *MockIDatabaseAdapter) CreateResetPassword(email, code string, delay time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResetPassword", email, code, delay)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResetPassword indicates an expected call of CreateResetPassword.
func (mr *MockIDatabaseAdapterMockRecorder) CreateResetPassword(email, code, delay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResetPassword", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateResetPassword), email, code, delay)
}

// CreateSalary mocks base method.
func (m *MockIDatabaseAdapter) CreateSalary(payload models.CreateSalary, userID, employeeID int64) (int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSalary", payload, userID, employeeID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateSalary indicates an expected call of CreateSalary.
func (mr *MockIDatabaseAdapterMockRecorder) CreateSalary(payload, userID, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSalary", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateSalary), payload, userID, employeeID)
}

// CreateSalaryCost mocks base method.
func (m *MockIDatabaseAdapter) CreateSalaryCost(payload models.CreateSalaryCost, userID, salaryID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSalaryCost", payload, userID, salaryID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSalaryCost indicates an expected call of CreateSalaryCost.
func (mr *MockIDatabaseAdapterMockRecorder) CreateSalaryCost(payload, userID, salaryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSalaryCost", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateSalaryCost), payload, userID, salaryID)
}

// CreateSalaryCostLabel mocks base method.
func (m *MockIDatabaseAdapter) CreateSalaryCostLabel(payload models.CreateSalaryCostLabel, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSalaryCostLabel", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSalaryCostLabel indicates an expected call of CreateSalaryCostLabel.
func (mr *MockIDatabaseAdapterMockRecorder) CreateSalaryCostLabel(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSalaryCostLabel", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateSalaryCostLabel), payload, userID)
}

// CreateScenario mocks base method.
func (m *MockIDatabaseAdapter) CreateScenario(payload models.CreateScenario, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScenario", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScenario indicates an expected call of CreateScenario.
func (mr *MockIDatabaseAdapterMockRecorder) CreateScenario(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScenario", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateScenario), payload, userID)
}

// CreateTransaction mocks base method.
func (m *MockIDatabaseAdapter) CreateTransaction(payload models.CreateTransaction, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockIDatabaseAdapterMockRecorder) CreateTransaction(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateTransaction), payload, userID)
}

// CreateUser mocks base method.
func (m *MockIDatabaseAdapter) CreateUser(email, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", email, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIDatabaseAdapterMockRecorder) CreateUser(email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateUser), email, password)
}

// CreateVat mocks base method.
func (m *MockIDatabaseAdapter) CreateVat(payload models.CreateVat, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVat", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVat indicates an expected call of CreateVat.
func (mr *MockIDatabaseAdapterMockRecorder) CreateVat(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVat", reflect.TypeOf((*MockIDatabaseAdapter)(nil).CreateVat), payload, userID)
}

// DeleteBankAccount mocks base method.
func (m *MockIDatabaseAdapter) DeleteBankAccount(userID, bankAccountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBankAccount", userID, bankAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBankAccount indicates an expected call of DeleteBankAccount.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteBankAccount(userID, bankAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBankAccount", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteBankAccount), userID, bankAccountID)
}

// DeleteEmployee mocks base method.
func (m *MockIDatabaseAdapter) DeleteEmployee(userID, employeeID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployee", userID, employeeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployee indicates an expected call of DeleteEmployee.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteEmployee(userID, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployee", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteEmployee), userID, employeeID)
}

// DeleteForecastExclusion mocks base method.
func (m *MockIDatabaseAdapter) DeleteForecastExclusion(payload models.CreateForecastExclusion, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteForecastExclusion", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteForecastExclusion indicates an expected call of DeleteForecastExclusion.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteForecastExclusion(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteForecastExclusion", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteForecastExclusion), payload, userID)
}

// DeleteRefreshToken mocks base method.
func (m *MockIDatabaseAdapter) DeleteRefreshToken(userID int64, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", userID, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteRefreshToken(userID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteRefreshToken), userID, tokenID)
}

// DeleteRegistration mocks base method.
func (m *MockIDatabaseAdapter) DeleteRegistration(registrationID int64, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegistration", registrationID, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegistration indicates an expected call of DeleteRegistration.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteRegistration(registrationID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegistration", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteRegistration), registrationID, email)
}

// DeleteResetPassword mocks base method.
func (m *MockIDatabaseAdapter) DeleteResetPassword(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResetPassword", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResetPassword indicates an expected call of DeleteResetPassword.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteResetPassword(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResetPassword", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteResetPassword), email)
}

// DeleteSalary mocks base method.
func (m *MockIDatabaseAdapter) DeleteSalary(existingSalary *models.Salary, userID int64) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSalary", existingSalary, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteSalary indicates an expected call of DeleteSalary.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteSalary(existingSalary, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSalary", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteSalary), existingSalary, userID)
}

// DeleteSalaryCost mocks base method.
func (m *MockIDatabaseAdapter) DeleteSalaryCost(userID, salaryCostID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSalaryCost", userID, salaryCostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSalaryCost indicates an expected call of DeleteSalaryCost.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteSalaryCost(userID, salaryCostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSalaryCost", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteSalaryCost), userID, salaryCostID)
}

// DeleteSalaryCostLabel mocks base method.
func (m *MockIDatabaseAdapter) DeleteSalaryCostLabel(userID, salaryCostLabelID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSalaryCostLabel", userID, salaryCostLabelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSalaryCostLabel indicates an expected call of DeleteSalaryCostLabel.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteSalaryCostLabel(userID, salaryCostLabelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSalaryCostLabel", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteSalaryCostLabel), userID, salaryCostLabelID)
}

// DeleteSalaryCostsBySalaryID mocks base method.
func (m *MockIDatabaseAdapter) DeleteSalaryCostsBySalaryID(salaryID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSalaryCostsBySalaryID", salaryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSalaryCostsBySalaryID indicates an expected call of DeleteSalaryCostsBySalaryID.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteSalaryCostsBySalaryID(salaryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSalaryCostsBySalaryID", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteSalaryCostsBySalaryID), salaryID)
}

// DeleteScenario mocks base method.
func (m *MockIDatabaseAdapter) DeleteScenario(userID, scenarioID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScenario", userID, scenarioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScenario indicates an expected call of DeleteScenario.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteScenario(userID, scenarioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScenario", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteScenario), userID, scenarioID)
}

// DeleteTransaction mocks base method.
func (m *MockIDatabaseAdapter) DeleteTransaction(userID, transactionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", userID, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteTransaction(userID, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteTransaction), userID, transactionID)
}

// DeleteVat mocks base method.
func (m *MockIDatabaseAdapter) DeleteVat(userID, vatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVat", userID, vatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVat indicates an expected call of DeleteVat.
func (mr *MockIDatabaseAdapterMockRecorder) DeleteVat(userID, vatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVat", reflect.TypeOf((*MockIDatabaseAdapter)(nil).DeleteVat), userID, vatID)
}

// GetBankAccount mocks base method.
func (m *MockIDatabaseAdapter) GetBankAccount(userID, bankAccountID int64) (*models.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankAccount", userID, bankAccountID)
	ret0, _ := ret[0].(*models.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBankAccount indicates an expected call of GetBankAccount.
func (mr *MockIDatabaseAdapterMockRecorder) GetBankAccount(userID, bankAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankAccount", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetBankAccount), userID, bankAccountID)
}

// GetCategory mocks base method.
func (m *MockIDatabaseAdapter) GetCategory(userID, categoryID int64) (*models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", userID, categoryID)
	ret0, _ := ret[0].(*models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockIDatabaseAdapterMockRecorder) GetCategory(userID, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetCategory), userID, categoryID)
}

// GetCurrency mocks base method.
func (m *MockIDatabaseAdapter) GetCurrency(currencyID int64) (*models.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency", currencyID)
	ret0, _ := ret[0].(*models.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrency indicates an expected call of GetCurrency.
func (mr *MockIDatabaseAdapterMockRecorder) GetCurrency(currencyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetCurrency), currencyID)
}

// GetDefaultScenario mocks base method.
func (m *MockIDatabaseAdapter) GetDefaultScenario(userID int64) (*models.Scenario, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultScenario", userID)
	ret0, _ := ret[0].(*models.Scenario)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultScenario indicates an expected call of GetDefaultScenario.
func (mr *MockIDatabaseAdapterMockRecorder) GetDefaultScenario(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultScenario", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetDefaultScenario), userID)
}

// GetEmployee mocks base method.
func (m *MockIDatabaseAdapter) GetEmployee(userID, employeeID int64) (*models.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployee", userID, employeeID)
	ret0, _ := ret[0].(*models.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployee indicates an expected call of GetEmployee.
func (mr *MockIDatabaseAdapterMockRecorder) GetEmployee(userID, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployee", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetEmployee), userID, employeeID)
}

// GetFiatRate mocks base method.
func (m *MockIDatabaseAdapter) GetFiatRate(base, target string) (*models.FiatRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFiatRate", base, target)
	ret0, _ := ret[0].(*models.FiatRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFiatRate indicates an expected call of GetFiatRate.
func (mr *MockIDatabaseAdapterMockRecorder) GetFiatRate(base, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFiatRate", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetFiatRate), base, target)
}

// GetOrganisation mocks base method.
func (m *MockIDatabaseAdapter) GetOrganisation(userID, organisationID int64) (*models.Organisation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganisation", userID, organisationID)
	ret0, _ := ret[0].(*models.Organisation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganisation indicates an expected call of GetOrganisation.
func (mr *MockIDatabaseAdapterMockRecorder) GetOrganisation(userID, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganisation", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetOrganisation), userID, organisationID)
}

// GetProfile mocks base method.
func (m *MockIDatabaseAdapter) GetProfile(userID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockIDatabaseAdapterMockRecorder) GetProfile(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetProfile), userID)
}

// GetSalary mocks base method.
func (m *MockIDatabaseAdapter) GetSalary(userID, salaryID int64) (*models.Salary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalary", userID, salaryID)
	ret0, _ := ret[0].(*models.Salary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalary indicates an expected call of GetSalary.
func (mr *MockIDatabaseAdapterMockRecorder) GetSalary(userID, salaryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalary", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetSalary), userID, salaryID)
}

// GetSalaryCost mocks base method.
func (m *MockIDatabaseAdapter) GetSalaryCost(userID, salaryCostID int64) (*models.SalaryCost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalaryCost", userID, salaryCostID)
	ret0, _ := ret[0].(*models.SalaryCost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalaryCost indicates an expected call of GetSalaryCost.
func (mr *MockIDatabaseAdapterMockRecorder) GetSalaryCost(userID, salaryCostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalaryCost", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetSalaryCost), userID, salaryCostID)
}

// GetSalaryCostLabel mocks base method.
func (m *MockIDatabaseAdapter) GetSalaryCostLabel(userID, salaryCostLabelID int64) (*models.SalaryCostLabel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalaryCostLabel", userID, salaryCostLabelID)
	ret0, _ := ret[0].(*models.SalaryCostLabel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalaryCostLabel indicates an expected call of GetSalaryCostLabel.
func (mr *MockIDatabaseAdapterMockRecorder) GetSalaryCostLabel(userID, salaryCostLabelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalaryCostLabel", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetSalaryCostLabel), userID, salaryCostLabelID)
}

// GetScenario mocks base method.
func (m *MockIDatabaseAdapter) GetScenario(userID, scenarioID int64) (*models.Scenario, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScenario", userID, scenarioID)
	ret0, _ := ret[0].(*models.Scenario)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScenario indicates an expected call of GetScenario.
func (mr *MockIDatabaseAdapterMockRecorder) GetScenario(userID, scenarioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScenario", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetScenario), userID, scenarioID)
}

// GetTransaction mocks base method.
func (m *MockIDatabaseAdapter) GetTransaction(userID, transactionID int64) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", userID, transactionID)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockIDatabaseAdapterMockRecorder) GetTransaction(userID, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetTransaction), userID, transactionID)
}

// GetUserPasswordByEMail mocks base method.
func (m *MockIDatabaseAdapter) GetUserPasswordByEMail(email string) (*models.Login, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPasswordByEMail", email)
	ret0, _ := ret[0].(*models.Login)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPasswordByEMail indicates an expected call of GetUserPasswordByEMail.
func (mr *MockIDatabaseAdapterMockRecorder) GetUserPasswordByEMail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPasswordByEMail", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetUserPasswordByEMail), email)
}

// GetUsersUsingScenario mocks base method.
func (m *MockIDatabaseAdapter) GetUsersUsingScenario(scenarioID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersUsingScenario", scenarioID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersUsingScenario indicates an expected call of GetUsersUsingScenario.
func (mr *MockIDatabaseAdapterMockRecorder) GetUsersUsingScenario(scenarioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersUsingScenario", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetUsersUsingScenario), scenarioID)
}

// GetVat mocks base method.
func (m *MockIDatabaseAdapter) GetVat(userID, vatID int64) (*models.Vat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVat", userID, vatID)
	ret0, _ := ret[0].(*models.Vat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVat indicates an expected call of GetVat.
func (mr *MockIDatabaseAdapterMockRecorder) GetVat(userID, vatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVat", reflect.TypeOf((*MockIDatabaseAdapter)(nil).GetVat), userID, vatID)
}

// IsScenarioInUse mocks base method.
func (m *MockIDatabaseAdapter) IsScenarioInUse(scenarioID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsScenarioInUse", scenarioID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsScenarioInUse indicates an expected call of IsScenarioInUse.
func (mr *MockIDatabaseAdapterMockRecorder) IsScenarioInUse(scenarioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsScenarioInUse", reflect.TypeOf((*MockIDatabaseAdapter)(nil).IsScenarioInUse), scenarioID)
}

// ListBankAccounts mocks base method.
func (m *MockIDatabaseAdapter) ListBankAccounts(userID int64) ([]models.BankAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBankAccounts", userID)
	ret0, _ := ret[0].([]models.BankAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBankAccounts indicates an expected call of ListBankAccounts.
func (mr *MockIDatabaseAdapterMockRecorder) ListBankAccounts(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBankAccounts", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListBankAccounts), userID)
}

// ListCategories mocks base method.
func (m *MockIDatabaseAdapter) ListCategories(userID, page, limit int64) ([]models.Category, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", userID, page, limit)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockIDatabaseAdapterMockRecorder) ListCategories(userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListCategories), userID, page, limit)
}

// ListCurrencies mocks base method.
func (m *MockIDatabaseAdapter) ListCurrencies(userID int64) ([]models.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCurrencies", userID)
	ret0, _ := ret[0].([]models.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCurrencies indicates an expected call of ListCurrencies.
func (mr *MockIDatabaseAdapterMockRecorder) ListCurrencies(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCurrencies", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListCurrencies), userID)
}

// ListEmployees mocks base method.
func (m *MockIDatabaseAdapter) ListEmployees(userID, page, limit int64, sortBy, sortOrder string) ([]models.Employee, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployees", userID, page, limit, sortBy, sortOrder)
	ret0, _ := ret[0].([]models.Employee)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEmployees indicates an expected call of ListEmployees.
func (mr *MockIDatabaseAdapterMockRecorder) ListEmployees(userID, page, limit, sortBy, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployees", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListEmployees), userID, page, limit, sortBy, sortOrder)
}

// ListFiatRates mocks base method.
func (m *MockIDatabaseAdapter) ListFiatRates(base string) ([]models.FiatRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiatRates", base)
	ret0, _ := ret[0].([]models.FiatRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiatRates indicates an expected call of ListFiatRates.
func (mr *MockIDatabaseAdapterMockRecorder) ListFiatRates(base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiatRates", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListFiatRates), base)
}

// ListForecastDetails mocks base method.
func (m *MockIDatabaseAdapter) ListForecastDetails(userID, limit int64) ([]models.ForecastDatabaseDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForecastDetails", userID, limit)
	ret0, _ := ret[0].([]models.ForecastDatabaseDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForecastDetails indicates an expected call of ListForecastDetails.
func (mr *MockIDatabaseAdapterMockRecorder) ListForecastDetails(userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForecastDetails", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListForecastDetails), userID, limit)
}

// ListForecastExclusions mocks base method.
func (m *MockIDatabaseAdapter) ListForecastExclusions(userID, relatedID int64, relatedTable string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForecastExclusions", userID, relatedID, relatedTable)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForecastExclusions indicates an expected call of ListForecastExclusions.
func (mr *MockIDatabaseAdapterMockRecorder) ListForecastExclusions(userID, relatedID, relatedTable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForecastExclusions", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListForecastExclusions), userID, relatedID, relatedTable)
}

// ListForecasts mocks base method.
func (m *MockIDatabaseAdapter) ListForecasts(userID, limit int64) ([]models.Forecast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForecasts", userID, limit)
	ret0, _ := ret[0].([]models.Forecast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForecasts indicates an expected call of ListForecasts.
func (mr *MockIDatabaseAdapterMockRecorder) ListForecasts(userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForecasts", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListForecasts), userID, limit)
}

// ListOrganisations mocks base method.
func (m *MockIDatabaseAdapter) ListOrganisations(userID, page, limit int64) ([]models.Organisation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganisations", userID, page, limit)
	ret0, _ := ret[0].([]models.Organisation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrganisations indicates an expected call of ListOrganisations.
func (mr *MockIDatabaseAdapterMockRecorder) ListOrganisations(userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganisations", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListOrganisations), userID, page, limit)
}

// ListSalaries mocks base method.
func (m *MockIDatabaseAdapter) ListSalaries(userID, employeeID, page, limit int64) ([]models.Salary, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalaries", userID, employeeID, page, limit)
	ret0, _ := ret[0].([]models.Salary)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSalaries indicates an expected call of ListSalaries.
func (mr *MockIDatabaseAdapterMockRecorder) ListSalaries(userID, employeeID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalaries", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListSalaries), userID, employeeID, page, limit)
}

// ListSalaryCostBaseIDs mocks base method.
func (m *MockIDatabaseAdapter) ListSalaryCostBaseIDs(costID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalaryCostBaseIDs", costID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSalaryCostBaseIDs indicates an expected call of ListSalaryCostBaseIDs.
func (mr *MockIDatabaseAdapterMockRecorder) ListSalaryCostBaseIDs(costID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalaryCostBaseIDs", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListSalaryCostBaseIDs), costID)
}

// ListSalaryCostDetails mocks base method.
func (m *MockIDatabaseAdapter) ListSalaryCostDetails(salaryCostID int64) ([]models.SalaryCostDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalaryCostDetails", salaryCostID)
	ret0, _ := ret[0].([]models.SalaryCostDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSalaryCostDetails indicates an expected call of ListSalaryCostDetails.
func (mr *MockIDatabaseAdapterMockRecorder) ListSalaryCostDetails(salaryCostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalaryCostDetails", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListSalaryCostDetails), salaryCostID)
}

// ListSalaryCostLabels mocks base method.
func (m *MockIDatabaseAdapter) ListSalaryCostLabels(userID, page, limit int64) ([]models.SalaryCostLabel, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalaryCostLabels", userID, page, limit)
	ret0, _ := ret[0].([]models.SalaryCostLabel)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSalaryCostLabels indicates an expected call of ListSalaryCostLabels.
func (mr *MockIDatabaseAdapterMockRecorder) ListSalaryCostLabels(userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalaryCostLabels", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListSalaryCostLabels), userID, page, limit)
}

// ListSalaryCosts mocks base method.
func (m *MockIDatabaseAdapter) ListSalaryCosts(userID, salaryID, page, limit int64) ([]models.SalaryCost, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalaryCosts", userID, salaryID, page, limit)
	ret0, _ := ret[0].([]models.SalaryCost)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSalaryCosts indicates an expected call of ListSalaryCosts.
func (mr *MockIDatabaseAdapterMockRecorder) ListSalaryCosts(userID, salaryID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalaryCosts", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListSalaryCosts), userID, salaryID, page, limit)
}

// ListScenarios mocks base method.
func (m *MockIDatabaseAdapter) ListScenarios(userID int64) ([]models.ScenarioListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScenarios", userID)
	ret0, _ := ret[0].([]models.ScenarioListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScenarios indicates an expected call of ListScenarios.
func (mr *MockIDatabaseAdapterMockRecorder) ListScenarios(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScenarios", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListScenarios), userID)
}

// ListTransactions mocks base method.
func (m *MockIDatabaseAdapter) ListTransactions(userID, page, limit int64, sortBy, sortOrder string) ([]models.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", userID, page, limit, sortBy, sortOrder)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockIDatabaseAdapterMockRecorder) ListTransactions(userID, page, limit, sortBy, sortOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListTransactions), userID, page, limit, sortBy, sortOrder)
}

// ListVats mocks base method.
func (m *MockIDatabaseAdapter) ListVats(userID int64) ([]models.Vat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVats", userID)
	ret0, _ := ret[0].([]models.Vat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVats indicates an expected call of ListVats.
func (mr *MockIDatabaseAdapterMockRecorder) ListVats(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVats", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ListVats), userID)
}

// RefreshSalaryCostDetails mocks base method.
func (m *MockIDatabaseAdapter) RefreshSalaryCostDetails(userID, salaryID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshSalaryCostDetails", userID, salaryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshSalaryCostDetails indicates an expected call of RefreshSalaryCostDetails.
func (mr *MockIDatabaseAdapterMockRecorder) RefreshSalaryCostDetails(userID, salaryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSalaryCostDetails", reflect.TypeOf((*MockIDatabaseAdapter)(nil).RefreshSalaryCostDetails), userID, salaryID)
}

// ResetPassword mocks base method.
func (m *MockIDatabaseAdapter) ResetPassword(password, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", password, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockIDatabaseAdapterMockRecorder) ResetPassword(password, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ResetPassword), password, email)
}

// SetSalaryCostBaseLinks mocks base method.
func (m *MockIDatabaseAdapter) SetSalaryCostBaseLinks(costID int64, baseIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSalaryCostBaseLinks", costID, baseIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSalaryCostBaseLinks indicates an expected call of SetSalaryCostBaseLinks.
func (mr *MockIDatabaseAdapterMockRecorder) SetSalaryCostBaseLinks(costID, baseIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSalaryCostBaseLinks", reflect.TypeOf((*MockIDatabaseAdapter)(nil).SetSalaryCostBaseLinks), costID, baseIDs)
}

// SetUserCurrentOrganisation mocks base method.
func (m *MockIDatabaseAdapter) SetUserCurrentOrganisation(userID, organisationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserCurrentOrganisation", userID, organisationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserCurrentOrganisation indicates an expected call of SetUserCurrentOrganisation.
func (mr *MockIDatabaseAdapterMockRecorder) SetUserCurrentOrganisation(userID, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserCurrentOrganisation", reflect.TypeOf((*MockIDatabaseAdapter)(nil).SetUserCurrentOrganisation), userID, organisationID)
}

// SetUserCurrentScenario mocks base method.
func (m *MockIDatabaseAdapter) SetUserCurrentScenario(userID, scenarioID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserCurrentScenario", userID, scenarioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserCurrentScenario indicates an expected call of SetUserCurrentScenario.
func (mr *MockIDatabaseAdapterMockRecorder) SetUserCurrentScenario(userID, scenarioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserCurrentScenario", reflect.TypeOf((*MockIDatabaseAdapter)(nil).SetUserCurrentScenario), userID, scenarioID)
}

// StoreRefreshTokenID mocks base method.
func (m *MockIDatabaseAdapter) StoreRefreshTokenID(userID int64, tokenId string, expirationTime time.Time, deviceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefreshTokenID", userID, tokenId, expirationTime, deviceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefreshTokenID indicates an expected call of StoreRefreshTokenID.
func (mr *MockIDatabaseAdapterMockRecorder) StoreRefreshTokenID(userID, tokenId, expirationTime, deviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefreshTokenID", reflect.TypeOf((*MockIDatabaseAdapter)(nil).StoreRefreshTokenID), userID, tokenId, expirationTime, deviceName)
}

// UpdateBankAccount mocks base method.
func (m *MockIDatabaseAdapter) UpdateBankAccount(payload models.UpdateBankAccount, userID, bankAccountID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBankAccount", payload, userID, bankAccountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBankAccount indicates an expected call of UpdateBankAccount.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateBankAccount(payload, userID, bankAccountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBankAccount", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateBankAccount), payload, userID, bankAccountID)
}

// UpdateCategory mocks base method.
func (m *MockIDatabaseAdapter) UpdateCategory(payload models.UpdateCategory, userID, categoryID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", payload, userID, categoryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateCategory(payload, userID, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateCategory), payload, userID, categoryID)
}

// UpdateCurrency mocks base method.
func (m *MockIDatabaseAdapter) UpdateCurrency(payload models.UpdateCurrency, currencyID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrency", payload, currencyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCurrency indicates an expected call of UpdateCurrency.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateCurrency(payload, currencyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrency", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateCurrency), payload, currencyID)
}

// UpdateEmployee mocks base method.
func (m *MockIDatabaseAdapter) UpdateEmployee(payload models.UpdateEmployee, userID, employeeID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployee", payload, userID, employeeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmployee indicates an expected call of UpdateEmployee.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateEmployee(payload, userID, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployee", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateEmployee), payload, userID, employeeID)
}

// UpdateOrganisation mocks base method.
func (m *MockIDatabaseAdapter) UpdateOrganisation(payload models.UpdateOrganisation, userID, organisationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganisation", payload, userID, organisationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrganisation indicates an expected call of UpdateOrganisation.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateOrganisation(payload, userID, organisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganisation", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateOrganisation), payload, userID, organisationID)
}

// UpdatePassword mocks base method.
func (m *MockIDatabaseAdapter) UpdatePassword(userID int64, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", userID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockIDatabaseAdapterMockRecorder) UpdatePassword(userID, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdatePassword), userID, password)
}

// UpdateProfile mocks base method.
func (m *MockIDatabaseAdapter) UpdateProfile(payload models.UpdateUser, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", payload, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateProfile(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateProfile), payload, userID)
}

// UpdateSalary mocks base method.
func (m *MockIDatabaseAdapter) UpdateSalary(payload models.UpdateSalary, employeeID, salaryID int64) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSalary", payload, employeeID, salaryID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateSalary indicates an expected call of UpdateSalary.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateSalary(payload, employeeID, salaryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSalary", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateSalary), payload, employeeID, salaryID)
}

// UpdateSalaryCost mocks base method.
func (m *MockIDatabaseAdapter) UpdateSalaryCost(payload models.CreateSalaryCost, userID, salaryCostID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSalaryCost", payload, userID, salaryCostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSalaryCost indicates an expected call of UpdateSalaryCost.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateSalaryCost(payload, userID, salaryCostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSalaryCost", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateSalaryCost), payload, userID, salaryCostID)
}

// UpdateSalaryCostLabel mocks base method.
func (m *MockIDatabaseAdapter) UpdateSalaryCostLabel(payload models.CreateSalaryCostLabel, userID, salaryCostLabelID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSalaryCostLabel", payload, userID, salaryCostLabelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSalaryCostLabel indicates an expected call of UpdateSalaryCostLabel.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateSalaryCostLabel(payload, userID, salaryCostLabelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSalaryCostLabel", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateSalaryCostLabel), payload, userID, salaryCostLabelID)
}

// UpdateScenario mocks base method.
func (m *MockIDatabaseAdapter) UpdateScenario(payload models.UpdateScenario, userID, scenarioID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScenario", payload, userID, scenarioID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScenario indicates an expected call of UpdateScenario.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateScenario(payload, userID, scenarioID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScenario", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateScenario), payload, userID, scenarioID)
}

// UpdateTransaction mocks base method.
func (m *MockIDatabaseAdapter) UpdateTransaction(payload models.UpdateTransaction, userID, transactionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", payload, userID, transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateTransaction(payload, userID, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateTransaction), payload, userID, transactionID)
}

// UpdateVat mocks base method.
func (m *MockIDatabaseAdapter) UpdateVat(payload models.UpdateVat, userID, vatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVat", payload, userID, vatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVat indicates an expected call of UpdateVat.
func (mr *MockIDatabaseAdapterMockRecorder) UpdateVat(payload, userID, vatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVat", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpdateVat), payload, userID, vatID)
}

// UpsertFiatRate mocks base method.
func (m *MockIDatabaseAdapter) UpsertFiatRate(payload models.CreateFiatRate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFiatRate", payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFiatRate indicates an expected call of UpsertFiatRate.
func (mr *MockIDatabaseAdapterMockRecorder) UpsertFiatRate(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFiatRate", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpsertFiatRate), payload)
}

// UpsertForecast mocks base method.
func (m *MockIDatabaseAdapter) UpsertForecast(payload models.CreateForecast, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertForecast", payload, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertForecast indicates an expected call of UpsertForecast.
func (mr *MockIDatabaseAdapterMockRecorder) UpsertForecast(payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertForecast", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpsertForecast), payload, userID)
}

// UpsertForecastDetail mocks base method.
func (m *MockIDatabaseAdapter) UpsertForecastDetail(payload models.CreateForecastDetail, userID, forecastID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertForecastDetail", payload, userID, forecastID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertForecastDetail indicates an expected call of UpsertForecastDetail.
func (mr *MockIDatabaseAdapterMockRecorder) UpsertForecastDetail(payload, userID, forecastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertForecastDetail", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpsertForecastDetail), payload, userID, forecastID)
}

// UpsertSalaryCostDetails mocks base method.
func (m *MockIDatabaseAdapter) UpsertSalaryCostDetails(payload models.CreateSalaryCostDetail) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSalaryCostDetails", payload)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSalaryCostDetails indicates an expected call of UpsertSalaryCostDetails.
func (mr *MockIDatabaseAdapterMockRecorder) UpsertSalaryCostDetails(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSalaryCostDetails", reflect.TypeOf((*MockIDatabaseAdapter)(nil).UpsertSalaryCostDetails), payload)
}

// ValidateRegistration mocks base method.
func (m *MockIDatabaseAdapter) ValidateRegistration(email, code string, validity time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRegistration", email, code, validity)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateRegistration indicates an expected call of ValidateRegistration.
func (mr *MockIDatabaseAdapterMockRecorder) ValidateRegistration(email, code, validity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRegistration", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ValidateRegistration), email, code, validity)
}

// ValidateResetPassword mocks base method.
func (m *MockIDatabaseAdapter) ValidateResetPassword(email, code string, validity time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateResetPassword", email, code, validity)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateResetPassword indicates an expected call of ValidateResetPassword.
func (mr *MockIDatabaseAdapterMockRecorder) ValidateResetPassword(email, code, validity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateResetPassword", reflect.TypeOf((*MockIDatabaseAdapter)(nil).ValidateResetPassword), email, code, validity)
}
