// Code generated by MockGen. DO NOT EDIT.
// Source: liquiswiss/internal/adapter/email_adapter (interfaces: IEmailAdapter)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination ../../mocks/email_adapter.go liquiswiss/internal/adapter/email_adapter IEmailAdapter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIEmailAdapter is a mock of IEmailAdapter interface.
type MockIEmailAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockIEmailAdapterMockRecorder
	isgomock struct{}
}

// MockIEmailAdapterMockRecorder is the mock recorder for MockIEmailAdapter.
type MockIEmailAdapterMockRecorder struct {
	mock *MockIEmailAdapter
}

// NewMockIEmailAdapter creates a new mock instance.
func NewMockIEmailAdapter(ctrl *gomock.Controller) *MockIEmailAdapter {
	mock := &MockIEmailAdapter{ctrl: ctrl}
	mock.recorder = &MockIEmailAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEmailAdapter) EXPECT() *MockIEmailAdapterMockRecorder {
	return m.recorder
}

// SendInvitationMail mocks base method.
func (m *MockIEmailAdapter) SendInvitationMail(email, token, organisationName, invitedByName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvitationMail", email, token, organisationName, invitedByName)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInvitationMail indicates an expected call of SendInvitationMail.
func (mr *MockIEmailAdapterMockRecorder) SendInvitationMail(email, token, organisationName, invitedByName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvitationMail", reflect.TypeOf((*MockIEmailAdapter)(nil).SendInvitationMail), email, token, organisationName, invitedByName)
}

// SendPasswordResetMail mocks base method.
func (m *MockIEmailAdapter) SendPasswordResetMail(email, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetMail", email, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPasswordResetMail indicates an expected call of SendPasswordResetMail.
func (mr *MockIEmailAdapterMockRecorder) SendPasswordResetMail(email, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetMail", reflect.TypeOf((*MockIEmailAdapter)(nil).SendPasswordResetMail), email, code)
}

// SendRegistrationMail mocks base method.
func (m *MockIEmailAdapter) SendRegistrationMail(email, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRegistrationMail", email, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRegistrationMail indicates an expected call of SendRegistrationMail.
func (mr *MockIEmailAdapterMockRecorder) SendRegistrationMail(email, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRegistrationMail", reflect.TypeOf((*MockIEmailAdapter)(nil).SendRegistrationMail), email, code)
}
